# Generated by Django 6.1 on 2026-08-23 04:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('DRIVER', 'Registered Driver'), ('PASSENGER', 'Passenger')], default='PASSENGER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tbl_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(db_column='admin_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.CharField(db_column='email', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'tbl_admin',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(db_column='driver_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=15, unique=True)),
                ('email', models.CharField(db_column='email', max_length=50, unique=True)),
                ('license_number', models.CharField(db_column='license_number', max_length=30, unique=True)),
                ('vehicle_number', models.CharField(db_column='vehicle_number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(db_column='vehicle_type', default='auto', max_length=20)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Suspended', 'Suspended'), ('Rejected', 'Rejected')], db_column='verification_status', default='Pending', max_length=15)),
                ('qr_code', models.CharField(blank=True, db_column='qr_code', max_length=255, null=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reputation_score', models.FloatField(default=85.0, help_text='Dynamic safety score (0 to 100)')),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=5.0)),
                ('driver_photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='driver_docs/license/')),
                ('id_proof_doc', models.FileField(blank=True, null=True, upload_to='driver_docs/id_proof/')),
                ('police_clearance_doc', models.FileField(blank=True, null=True, upload_to='driver_docs/police_clearance/')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='driver_qrcodes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'tbl_driver',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(db_column='passenger_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.CharField(db_column='email', max_length=50, unique=True)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=15, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('emergency_contact_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_1_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_1_relation', models.CharField(blank=True, default='Family', max_length=50, null=True)),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_2_relation', models.CharField(blank=True, default='Friend', max_length=50, null=True)),
                ('emergency_contact_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_3_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_3_relation', models.CharField(blank=True, default='Guardian', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'tbl_passenger',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(db_column='trip_id', primary_key=True, serialize=False)),
                ('trip_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_location', models.CharField(db_column='start_location', default='Current Boarding Point', max_length=100)),
                ('end_location', models.CharField(blank=True, db_column='end_location', max_length=100, null=True)),
                ('start_time', models.DateTimeField(db_column='start_time', default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, db_column='end_time', null=True)),
                ('status', models.CharField(db_column='status', default='Ongoing', max_length=15)),
                ('pickup_location_name', models.CharField(default='Current Location', max_length=255)),
                ('pickup_latitude', models.FloatField(default=9.6843)),
                ('pickup_longitude', models.FloatField(default=76.6853)),
                ('drop_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_latitude', models.FloatField(blank=True, null=True)),
                ('drop_longitude', models.FloatField(blank=True, null=True)),
                ('live_latitude', models.FloatField(default=9.6843)),
                ('live_longitude', models.FloatField(default=76.6853)),
                ('live_updated_at', models.DateTimeField(auto_now=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to='core.driver')),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_passenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'tbl_trip',
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('sos_id', models.AutoField(db_column='sos_id', primary_key=True, serialize=False)),
                ('alert_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.CharField(db_column='location', default='Live GPS Distress Location', max_length=100)),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', default='Active', max_length=15)),
                ('latitude', models.FloatField(default=9.6843)),
                ('longitude', models.FloatField(default=76.6853)),
                ('location_name', models.CharField(default='Live GPS Distress Location', max_length=255)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('dispatched_services', models.CharField(default='Local Police (112) & Emergency Contacts', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_incidents', to='core.driver')),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_events', to='core.trip')),
            ],
            options={
                'verbose_name': 'SOS Alert',
                'verbose_name_plural': 'SOS Alerts',
                'db_table': 'tbl_sos_alert',
            },
        ),
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('rating_id', models.AutoField(db_column='rating_id', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='rating', default=5, help_text='Range 1-5')),
                ('review', models.TextField(blank=True, db_column='review', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('driving_safety_rating', models.PositiveSmallIntegerField(default=5)),
                ('vehicle_cleanliness_rating', models.PositiveSmallIntegerField(default=5)),
                ('behavior_rating', models.PositiveSmallIntegerField(default=5)),
                ('fare_honesty_rating', models.PositiveSmallIntegerField(default=5)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='core.driver')),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating_entry', to='core.trip')),
            ],
            options={
                'verbose_name': 'Rating & Review',
                'verbose_name_plural': 'Ratings & Reviews',
                'db_table': 'tbl_rating_review',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('incident_id', models.AutoField(db_column='incident_id', primary_key=True, serialize=False)),
                ('incident_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(db_column='incident_type', default='Unsafe Driving', max_length=30)),
                ('description', models.TextField(db_column='description')),
                ('status', models.CharField(db_column='status', default='Pending', max_length=15)),
                ('reported_at', models.DateTimeField(db_column='reported_at', default=django.utils.timezone.now)),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='core.trip')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'db_table': 'tbl_incident_report',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(db_column='complaint_id', primary_key=True, serialize=False)),
                ('complaint_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(db_column='description')),
                ('status', models.CharField(db_column='status', default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('OVERCHARGING', 'Overcharging / Unmetered Fare'), ('RECKLESS_DRIVING', 'Reckless or Dangerous Driving'), ('MISBEHAVIOR', 'Rude Behavior / Verbal Abuse'), ('HARASSMENT', 'Harassment / Safety Threat'), ('ROUTE_DEVIATION', 'Unauthorized Route Deviation'), ('REFUSAL', 'Refusal to Commute / Drop'), ('OTHER', 'Other Safety Issue')], default='MISBEHAVIOR', max_length=30)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='complaint_evidence/')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('penalty_points_deducted', models.IntegerField(default=5)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.driver')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.trip')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocuments',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('license_doc', models.CharField(db_column='license_doc', default='', max_length=255)),
                ('rc_doc', models.CharField(db_column='rc_doc', default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(db_column='uploaded_at', default=django.utils.timezone.now)),
                ('license_file', models.FileField(blank=True, null=True, upload_to='driver_docs/license/')),
                ('rc_file', models.FileField(blank=True, null=True, upload_to='vehicle_docs/rc/')),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.driver')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'db_table': 'tbl_vehicle_documents',
            },
        ),
    ]
