# Generated by Django 6.1 on 2026-08-24 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='rating',
            field=models.PositiveSmallIntegerField(db_column='rating', default=5, help_text='Range 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=9.6843, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=76.6853, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='live_latitude',
            field=models.DecimalField(decimal_places=6, default=9.6843, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='live_longitude',
            field=models.DecimalField(decimal_places=6, default=76.6853, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=9.6843, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=76.6853, max_digits=9),
        ),
    ]
