# Generated by Django 5.2.17 on 2026-10-02 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_trip_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, db_column='emergency_contact_2_name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, db_column='emergency_contact_2_phone', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^(\\+91[\\-\\s]?)?[6-9]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='passenger',
            name='emergency_contact_2_relation',
            field=models.CharField(blank=True, db_column='emergency_contact_2_relation', default='Friend', max_length=50, null=True),
        ),
    ]
