# Generated by Django 6.1 on 2026-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ratingreview_rating_alter_sosalert_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='boarding_address',
            field=models.CharField(blank=True, default='Current Boarding Point', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='boarding_latitude',
            field=models.DecimalField(decimal_places=6, default=9.6843, max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='boarding_longitude',
            field=models.DecimalField(decimal_places=6, default=76.6853, max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_latitude',
            field=models.DecimalField(decimal_places=6, default=9.6843, max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_longitude',
            field=models.DecimalField(decimal_places=6, default=76.6853, max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.CharField(blank=True, db_column='end_location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(blank=True, db_column='start_location', default='Current Boarding Point', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('SOS_Triggered', 'SOS Emergency Triggered'), ('Ongoing', 'Ongoing')], db_column='status', default='Active', max_length=20),
        ),
    ]
