# Generated by Django 5.2.17 on 2026-09-02 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_boarding_address_trip_boarding_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^(\\+91[\\-\\s]?)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(db_column='vehicle_number', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Vehicle number must follow standard license plate format (e.g. KL-05-AT-4455 or DL-01-A-1234).', regex='^[A-Za-z]{2}[-\\s]?[0-9]{1,2}[-\\s]?[A-Za-z]{1,3}[-\\s]?[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^(\\+91[\\-\\s]?)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('SOS_Triggered', 'SOS Emergency Triggered')], db_column='status', default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number.', regex='^(\\+91[\\-\\s]?)?[6-9]\\d{9}$')]),
        ),
    ]
